# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: INTEGRATE
author: Alexis Comber, Bui Thanh, Nick Malleson, Minh Le Kieu, Hang Nguyen
logo: ./assets/logo.jpg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: web.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - ./references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/Urban-Analytics/INTEGRATE
  branch: gh-pages  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  # favicon: "./assets/img/logo/favicon-32x32.png"  # A path to a favicon image
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  navbar_number_sections: true   # Add a number to each section in your left navbar
  google_analytics_id: ""        # A GA id that can be used to track book views.
  home_page_in_navbar: true      # Whether to include your home page in the left Navigation Bar
  baseurl: "https://github.com/Urban-Analytics/INTEGRATE"  # The base URL where your book will be hosted.
  navbar_footer_text: |
    <div>
    This website is powered by <a href="https://jupyterbook.org">Jupyter Book</a>
    </div>
  navbar:
    - text: Home
      url: intro.html
    - text: Presentations
      url: presentations/overview.html
    - text: Papers
      url: papers/overview.html
