# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: INTEGRATE
author: Alexis Comber, Bui Thanh, Nick Malleson, Minh Le Kieu, Hang Nguyen
logo: ./assets/logo.jpg

# Execution settings
execute:
  execute_notebooks: auto

# PDF build
latex:
  latex_documents:
    targetname: web.tex

# References
bibtex_bibfiles:
  - ./references.bib

# Repository info
repository:
  url: https://github.com/Urban-Analytics/INTEGRATE
  branch: gh-pages

# HTML options
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  navbar_number_sections: true
  home_page_in_toc: true    # show homepage in sidebar, with short label from _toc.yml
  extra_navbar: ""          # remove default "Powered by Jupyter Book" footer
  favicon: ./assets/logo.jpg

# Sphinx options (controls theme)
sphinx:
  config:
    html_theme_options:
      header_navigation:
        - text: Home
          url: intro.html
        - text: Presentations
          url: presentations/overview.html
        - text: Papers
          url: papers/overview.html
